from subprocess import call
for i in range(5):
    out = open('gnu.gp', 'w')
    out.write('set term wxt size 800,800\n')
    out.write('set size 1.2, 1.2\n')
    out.write('set key rmargin\n')
    out.write('set xlabel \'Execution time criterion weight\'\n')
    out.write('set ylabel \'Accuracy criterion weight\'\n')
    out.write('set zlabel \'Detail\'\n')
    out.write('set size square\n')
    # out.write('set xrange[0:1]\n')
    # out.write('set yrange[0:1]\n')
    out2 = open('gnu2.gp', 'w')
    out2.write('set term wxt size 800,800\n')
    out2.write('set size 1.2, 1.2\n')
    out2.write('set key rmargin\n')
    out2.write('set xlabel \'Execution time criterion weight\'\n')
    out2.write('set ylabel \'Accuracy criterion weight\'\n')
    out2.write('set zlabel \'Detail\'\n')
    out2.write('set size square\n')
    out.write('set term pngcairo\n')
    out.write('set output \'rank_{0:d}_TDA.png\'\n'.format(i))
    out.write("plot \"<awk '{if($"+str(i)+"==0){print $61,$63}}' TDA_ranks_weights.dat\" t '0'")
    for x in range(1, 60):  # Plots weights (time vs accuracy) per alternative for one particular ranking. Change $2== for desired ranking. and file
        out.write(", \"<awk '{if($"+str(i)+"=="+str(x)+"){print $61,$63}}' TDA_ranks_weights.dat\" t 'Alternative "+str(x)+"'")
    out2.write('set term pngcairo\n')
    out2.write('set output \'alternative_{0:d}_TDA.png\'\n'.format(i))
    out2.write('plot ')
    for x in range(1, 60):  # Plots weights (time vs accuracy) per ranking of one particular alternative. Change ==29 for desired alternative. and file
        out2.write("\"<awk '{if($"+str(x)+"=="+str(i)+"){print $61,$63}}' TDA_ranks_weights.dat\" t 'Rank "+str(x)+"',")
    out.close()
    out2.close()
    call(["gnuplot", "gnu.gp"])
    call(["gnuplot", "gnu2.gp"])